server:
  port: 8080

logging:
  config: logback.xml

spring:
  main:
    banner-mode: console
  datasource:
    url: jdbc:h2:mem:students
    username: fiap_usr
    password: fiap_pwd
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"