CREATE TABLE STUDENT (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  subscription INTEGER(7) NOT NULL,
  code INTEGER(5) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE LIMIT_CARD (
  id INTEGER NOT NULL AUTO_INCREMENT,
  datetime_limit TIMESTAMP NOT NULL,
  value decimal(19,2) DEFAULT NULL,
  student_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (student_id) REFERENCES STUDENT(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TRANSACTION_CARD (
  id INTEGER NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(15) NOT NULL,
  datetime_transaction TIMESTAMP NOT NULL,
  value decimal(19,2) DEFAULT NULL,
  description VARCHAR(150),
  card_limit_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (card_limit_id) REFERENCES LIMIT_CARD(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;